'use strict';

class prhBusinessLine{
    //
}

// All businesslines
const BL_CROP_ANIMAL_HUNTING = 1;
const BL_FORESTRY_LOGGING = 2;
const BL_FISHING_AQUACULTURE = 3;
const BL_COAL_LIGNITE = 5;
const BL_PETROLEUM_NATGAS = 6;
const BL_METAL_ORES = 7;
const BL_OTHER_MINING_QUARRYING = 8;
const BL_MINING_SUPPORT = 9;
const BL_FOOD = 10;
const BL_BEVERAGES = 11;
const BL_TOBACCO = 12;
const BL_TEXTILES = 13;
const BL_APPAREL = 14;
const BL_LEATHER = 15;
const BL_WOOD = 16;
const BL_PAPER = 17;
const BL_PRINTING_REPRODUCTION = 18;
const BL_REFINED_PETROL = 19;
const BL_CHEMICALS = 20;
const BL_PHARMACEUTICAL_PRODS = 21;
const BL_PLASTIC_RUBBER = 22;
const BL_NONMETALLIC_MINERAL = 23;
const BL_BASICMETALS = 24;
const BL_METAL_PRODS = 25;
const BL_OPTOELECTRONICS = 26;
const BL_ELECTRICAL_EQUIP = 27;
const BL_MACHINERY_EQUIP = 28;
const BL_MOTORVEHICLES_TRAILERS = 29;
const BL_OTHER_TRANSPORT = 30;
const BL_FURNITURE = 31;
const BL_OTHER_MANUFACTURE = 32;
const BL_MACHINERY_INSTALL_REPAIR = 33;
const BL_ELECTRICITY_GAS_STEAM_AC = 35;
const BL_WATERSUPPLY = 36;
const BL_SEWERAGE = 37;
const BL_WASTE_COLLECTION_DISPOSAL = 38;
const BL_WASTE_REMEDIATION = 39;
const BL_BUILDINGS = 41;
const BL_CIVIL_ENGINEERING = 42;
const BL_SPECIAL_CONSTRUCTIONS = 43;
const BL_WHOLESALE_RETAIL_REPAIR_MOTORVEHICLES = 45;
const BL_WHOLESALE_TRADE = 46;
const BL_RETAIL_TRADE = 47;
const BL_LAND = 49;
const BL_WATER = 50;
const BL_AIR = 51;
const BL_WAREHOUSING = 52;
const BL_POSTAL_COURIER = 53;
const BL_ACCOMODATION = 55;
const BL_FOOD_BEVERAGE = 56;
const BL_PUBLISHING = 58;
const BL_TV_VIDEO_SOUND = 59;
const BL_BROADCASTING = 60;
const BL_TELECOMMUNICATIONS = 61;
const BL_COMPUTER_PROGRAMMING = 62;
const BL_INFORMATION_SERVICES = 63;
const BL_FINANCIAL = 64;
const BL_INSURANCE_PENSION = 65;
const BL_FINANCIAL_AUXIALIARY = 66;
const BL_REAL_ESTATE = 68;
const BL_LEGAL_ACCOUNTING = 69;
const BL_MANAGEMENT_CONSULTANCY = 70;
const BL_ARCHITECTURAL_ENGINEERING_ANALYSIS = 71;
const BL_SCIENTIFICAL_RESEARCH = 72;
const BL_ADVERTISING_RESEARCH = 73;
const BL_OTHER_PROFESSIONAL = 74;
const BL_VETERINARY = 75;
const BL_RENTAL_LEASING = 77;
const BL_EMPLOYMENT = 78;
const BL_TRAVELING = 79;
const BL_SECURITY_INVESTIGATION = 80;
const BL_BUILDINGS_LANDSCAPE = 81;
const BL_BUSINESS_SUPPORT = 82;
const BL_PUBLIC_ADMIN_DEFENCE_SOCIALSECURITY = 84;
const BL_EDUCATION = 85;
const BL_HUMAN_HEALTH = 86;
const BL_RESIDENTIAL_CARE = 87;
const BL_SOCIAL = 88;
const BL_ARTS_ENTERTAINMENT = 90;
const BL_LIBRARIES_MUSEUMS = 91;
const BL_GAMBLING_BETTING = 92;
const BL_SPORTS_AMUSEMENT = 93;
const BL_MEMBERSHIP = 94;
const BL_REPAIR_PERSONAL = 95;
const BL_OTHER_PERSONAL = 96;
const BL_HOUSEHOLD_SERVICES = 97;
const BL_INTERNATIONAL = 99;
const BL_UNKNOWN = 0;

// Business line collections
const BLC_AGRICULTURE_FORESTRY_FISHING = [
    BL_CROP_ANIMAL_HUNTING,
    BL_FORESTRY_LOGGING,
    BL_FISHING_AQUACULTURE
];
const BLC_MINING_QUARRYING = [
    BL_COAL_LIGNITE,
    BL_PETROLEUM_NATGAS,
    BL_METAL_ORES,
    BL_OTHER_MINING_QUARRYING,
    BL_MINING_SUPPORT
];
const BLC_MANUFACTURING = [
    BL_FOOD,
    BL_BEVERAGES,
    BL_TOBACCO,
    BL_TEXTILES,
    BL_APPAREL,
    BL_LEATHER,
    BL_WOOD,
    BL_PAPER,
    BL_PRINTING_REPRODUCTION,
    BL_REFINED_PETROL,
    BL_CHEMICALS,
    BL_PHARMACEUTICAL_PRODS,
    BL_PLASTIC_RUBBER,
    BL_NONMETALLIC_MINERAL,
    BL_BASICMETALS,
    BL_METAL_PRODS,
    BL_OPTOELECTRONICS,
    BL_ELECTRICAL_EQUIP,
    BL_MACHINERY_EQUIP,
    BL_MOTORVEHICLES_TRAILERS,
    BL_OTHER_TRANSPORT,
    BL_FURNITURE,
    BL_OTHER_MANUFACTURE,
    BL_MACHINERY_INSTALL_REPAIR
];
const BLC_ELECTRICITY_GAS_STEAM_AC = [
    BL_ELECTRICITY_GAS_STEAM_AC
];
const BLC_WATER_SEWERAGE_WASTE_REMEDIATION = [
    BL_WATERSUPPLY,
    BL_SEWERAGE,
    BL_WASTE_COLLECTION_DISPOSAL,
    BL_WASTE_REMEDIATION
];
const BLC_CONSTRUCTION = [
    BL_BUILDINGS,
    BL_CIVIL_ENGINEERING,
    BL_SPECIAL_CONSTRUCTIONS
];
const BLC_WHOLESALE_RETAIL_REPAIR_MOTORVEHICLES = [
    BL_WHOLESALE_RETAIL_REPAIR_MOTORVEHICLES,
    BL_WHOLESALE_TRADE,
    BL_RETAIL_TRADE
];
const BLC_TRANSPORTATION_STORAGE = [
    BL_LAND,
    BL_WATER,
    BL_AIR,
    BL_WAREHOUSING,
    BL_POSTAL_COURIER
];
const BLC_ACCOMMODATION_FOOD = [
    BL_ACCOMODATION,
    BL_FOOD_BEVERAGE
];
const BLC_INFORMATION_COMMUNICATION = [
    BL_PUBLISHING,
    BL_TV_VIDEO_SOUND,
    BL_BROADCASTING,
    BL_TELECOMMUNICATIONS,
    BL_COMPUTER_PROGRAMMING,
    BL_INFORMATION_SERVICES
];
const BLC_FINANCIAL_INSURANCE = [
    BL_FINANCIAL,
    BL_INSURANCE_PENSION,
    BL_FINANCIAL_AUXIALIARY
];
const BLC_REAL_ESTATE = [
    BL_REAL_ESTATE
];
const BLC_PROFESSIONAL_SCIENTIFIC_TECHNICAL = [
    BL_LEGAL_ACCOUNTING,
    BL_MANAGEMENT_CONSULTANCY,
    BL_ARCHITECTURAL_ENGINEERING_ANALYSIS,
    BL_SCIENTIFICAL_RESEARCH,
    BL_ADVERTISING_RESEARCH,
    BL_OTHER_PROFESSIONAL,
    BL_VETERINARY
];
const BLC_ADMINISTRATIVE_SUPPORT = [
    BL_RENTAL_LEASING,
    BL_EMPLOYMENT,
    BL_TRAVELING,
    BL_SECURITY_INVESTIGATION,
    BL_BUILDINGS_LANDSCAPE
];
const BLC_PUBLIC_ADMIN_DEFENCE_SOCIALSECURITY = [
    BL_PUBLIC_ADMIN_DEFENCE_SOCIALSECURITY
];
const BLC_EDUCATION = [
    BL_EDUCATION
];
const BLC_HEALTH_SOCIAL = [
    BL_HUMAN_HEALTH,
    BL_RESIDENTIAL_CARE,
    BL_SOCIAL
];
const BLC_ARTS_ENTERTAINMENT = [
    BL_ARTS_ENTERTAINMENT,
    BL_LIBRARIES_MUSEUMS,
    BL_GAMBLING_BETTING,
    BL_SPORTS_AMUSEMENT
];
const BLC_OTHER_SERVICES = [
    BL_MEMBERSHIP,
    BL_REPAIR_PERSONAL,
    BL_OTHER_PERSONAL
];
const BLC_HOUSEHOLD_SERVICES = [
    BL_HOUSEHOLD_SERVICES
];
const BLC_INTERNATIONAL = [
    BL_INTERNATIONAL
];
const BLC_UNKNOWN = [
    BL_UNKNOWN
];
